### ISSUE TITLE
Stopped working in Studio one 5

### ISSUE THREAD

**Issue by adinull** [Sian-Lee-SA/StudioOne-LaunchKey-MKIII#3]
Tried using the script in Studio one 5.2 and it stopped working. 
It looks like Studio one messed with the Atom files which caused the LaunchKey Mini Mk3 to stop working.

**Comment by Sian-Lee-SA** [comment]
This module doesnt actually rely on the Atom component, its just borrowed a bit of their code... That being said, I don't currently have version 5.2 installed so am unable to investigate but I'll try figure something out

**Comment by Sian-Lee-SA** [comment]
Try the latest commit as that had been merged for namespace fix if that is the issue

**Comment by ArsProgramma-private** [comment]
If you encounter any further issues on my fix with 5.2+ just text me or open an issue on my fork of this project, for i actually use 5.2 and am subscribed to Sphere. I may than PullRequest it back to here.

**Comment by Sian-Lee-SA** [comment]
> If you encounter any further issues on my fix with 5.2+ just text me or open an issue on my fork of this project, for i actually use 5.2 and am subscribed to Sphere. I may than PullRequest it back to here.

Thanks for your contribution!

**Comment by adinull** [comment]
The main issue has been resolved, however I encountered a minor problem when switching to Custom mode. Besides that the  latest commit works fine.

![LaunchKey - modeArr is undefined](https://user-images.githubusercontent.com/34815753/114087069-b2b97a80-98b3-11eb-80c0-4c72e46f76ca.jpg)

**Comment by Sian-Lee-SA** [comment]
Well thats good to hear! Will create another issue for your latest problem, in the mean time i will mark this one as closed.

**Comment by ArsProgramma-private** [comment]
@Qoima i just fixed the array-exception you mentioned.
Could you please test against my repo @
https://github.com/ArsProgramma/StudioOne-LaunchKey-Mini-MK3
and confirm that it works for you as well?
